test-warnings: true
ignore-paths:
  - marmoset/virt/
uses:
  - flask
pep257:
  run: true
  disable:
    - D203
    - D212
pep8:
  run: true
  full: true
pyroma:
  run: true
pylint:
  run: true
  enable:
    - unused-variable
  disable:
    - inconsistent-return-statements
dodgy:
  run: true
mccabe:
  run: true
